use_frameworks!

platform :ios, '8.0'

target 'AppsRouterLib_Example' do
  pod 'AppsRouterLib', :path => '../'

  target 'AppsRouterLib_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
